### ISSUE TITLE
Repo.find behavior

### ISSUE THREAD

**Issue by jessegrosjean** [automerge/automerge-repo-swift#84]
I've found two unexpected (to me) behaviors with repo.find().

First in this scenario repo.find() never finishes and never errors:

```
let repo = Repo(sharePolicy: SharePolicy.agreeable)
let websocket = WebSocketProvider(.init(reconnectOnError: false, loggingAt: .tracing))
await repo.addNetworkAdapter(adapter: websocket)
let handle = try await repo.find(id: DocumentId()) // never completes, never errors
print(handle)
```

And in this scenario (where I start web socket before repo.find()) I always successfully get a found handle with an associated document. This is unexpected because find seems to be acting more like create? I would expect some sort of "not found" error here, since the DocumentId should be unknown to the repo.

```
let repo = Repo(sharePolicy: SharePolicy.agreeable)
let websocket = WebSocketProvider(.init(reconnectOnError: false, loggingAt: .tracing))
await repo.addNetworkAdapter(adapter: websocket)
let handle = try await repo.find(id: DocumentId()) // always returns with a new document
print(handle)
```

I think maybe first is a bug. Not sure if second is expected or not.

**Comment by heckj** [comment]
My expectation in the first scenario is that `repo.find(id: DocumentId())` without a network connection should throw and `Unavailable` error - it shouldn't resolve into a handle.

The second may well be expected behavior, depending on what you're remote repo is providing. That's something where I'd want to see the traces that you've enabled to see what's returned. I'm not sure if a find with a DocumentId() is equivalent conceptually to "please create, and then return to me, a new document" for the JS version of automerge-repo.

The only scenario I've significantly worked is "create the doc", disconnect, reconnect later, "request the doc" and verify that the handle resolves and the doc contents are equivalent.

**Comment by heckj** [comment]
The first is definitely a bug - created a test that illustrates it (https://github.com/automerge/automerge-repo-swift/pull/85) 

The logic doesn't account for networking providers that have been added but aren't active to provide a response

**Comment by heckj** [comment]
I replicated the second in an integration test (now also in #85 - [second commit](https://github.com/automerge/automerge-repo-swift/pull/85/commits/bae1df8281a1d250dffcc61f84fe70c3fce2c765)) with a local instance of sync server, and it behaved exactly as you found as well. Since the remote repo returned a value, I believe that's expected behavior.

**Comment by heckj** [comment]
I'm aiming to get a fix in for the obvious find bug (failing to accommodate inactive network providers) and then cut a point release with the fixes
